- name: download stolon
  get_url: url="https://github.com/sorintlab/stolon/releases/download/v{{ stolon_version }}/stolon-v{{ stolon_version }}-linux-amd64.tar.gz" dest=/root/stolon-v{{ stolon_version }}-linux-amd64.tar.gz

- name: unpack stolon
  unarchive: copy=no src="/root/stolon-v{{ stolon_version }}-linux-amd64.tar.gz" dest={{ stolon_unarchive_prefix }}

- name: create a user
  user: name={{ stolon_keeper_user }}

- name: create a dir
  file: state=directory dest=/var/lib/stolon/data owner={{ stolon_keeper_user }}

- name: put systemd unit file to its destination
  template: src=stolon-keeper.service dest=/etc/systemd/system/stolon-keeper.service owner=root group=root mode=0644
  notify: systemctl daemon-reload

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers

- name: enable stolon-keeper service
  service: name=stolon-keeper enabled=yes state=started
  serial: 1
